* Introduction
HyprNixMacs is a configuration that centers around the usage of NixOS and Emacs.
Note that at the time of writing, I use hyprland as my window manager, but that
might change, and therefore hyprnixmacs may not be as accurate of a name.

** Why Not EXWM?
Because emacs is blocking, and I want to use wayland because it's much better and there's
much less cruft.

* Installation
Simply clone the contents of this repository to ~/etc/nixos/~ and run ~sudo nixos-rebuild switch~.
Note that afterwards you will need a ~$HOME/.password-store~ in user ~preston~ which has
an entry named ~Mail~, as well as a ~~/org/website/~ directory made by cloning my
[[https://github.com/ret2pop/ret2pop-website][ret2pop website]] repository to that location. Here are all the commands:
#+begin_src shell
  # run as root
  # create backup of hardware-configuration.nix and put it back there after
  git clone https://github.com/ret2pop/hyprnixmacs.git /etc/nixos/
  # put hardware-configuration.nix back in /etc/nixos
  nixos-rebuild switch
  su preston
  # copy over gpg and ssh keys
  git clone root@nullring.xyz:/var/git/password-store.git ~/.password-store/
  mkdir ~/org
  git clone https://github.com/ret2pop/ret2pop-website ~/org/website/
  # get music and put it in ~/music
#+end_src
this process can be highly automated via [[https://github.com/nix-community/nixos-anywhere][NixOS Anywhere]].
